version: '3'
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:4.0.1-ls107
    container_name: sabnzbd
    ports:
      - "8080:8080"
    volumes:
        - "/var/sabnzbd:/config"
        - "/media/epoch/Downloads/complete:/downloads"
        - "/media/epoch/Downloads/incomplete:/incomplete-downloads"
    environment:
      TZ: America/New_York
      PUID: 999
      PGID: 1005
    networks:
      - medianet
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    ports:
      - "9091:9091"
      - "51413:51413/tcp"
      - "51413:51413/udp"
      - "56181:56181"
    volumes:
        - "/var/lib/transmission-daemon:/config"
        - "/media/epoch/Downloads:/downloads"
    environment:
      TZ: America/New_York
      PUID: 999
      PGID: 1005
    networks:
      - medianet
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:arm32v7-3.0.9
    container_name: sonarr
    ports:
      - "8989:8989"
    volumes:
        - "/var/lib/sonarr:/config"
        - "/media/epoch/Downloads/complete:/downloads"
        - "/media/epoch/Videos/TV Shows:/tv"
    environment:
      TZ: America/New_York
      PUID: 999
      PGID: 1005
    networks:
      - medianet
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - "7878:7878"
    volumes:
        - "/var/lib/radarr:/config"
        - "/media/epoch/Downloads/complete:/downloads"
        - "/media/epoch/Videos/Movies:/movies"
    environment:
      TZ: America/New_York
      PUID: 999
      PGID: 1005
    networks:
      - medianet
    restart: unless-stopped

networks:
  medianet:
    name: medianet
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
