---
- hosts: localhost
  tasks:
    - name: Register cluster hosts
      import_tasks: add_hosts.yml
- hosts: cluster:gatewayed
  tasks:
  - name: Perform full upgrade
    apt:
      update_cache: yes
      upgrade: full
    become: true

- import_playbook: reboot.yml
