---
- hosts: localhost
  tasks:
    - name: Register cluster hosts
      import_tasks: add_hosts.yml
      when: "cluster_head_node not in groups['cluster']"
- hosts: gatewayed:cluster
  serial: 1
  tasks:
  - name: Reboot cluster
    reboot:
    become: true
