---
- hosts: localhost
  tasks:
    - name: Register cluster hosts
      import_tasks: add_hosts.yml
- hosts: gatewayed
  tasks:
  - name: Reboot gatewayed nodes
    reboot:
    become: true
- hosts: cluster
  tasks:
  - name: Reboot head node
    reboot:
    become: true
