all:
    vars:
        cluster_head_node: "{{ lookup('env', 'CLUSTER_HEAD_NODE') }}"
        cluster_node_2: "{{ lookup('env', 'CLUSTER_NODE_2') }}"
        cluster_node_3: "{{ lookup('env', 'CLUSTER_NODE_3') }}"
        cluster_node_4: "{{ lookup('env', 'CLUSTER_NODE_4') }}"
        cluster_user: "{{ lookup('env', 'CLUSTER_USER') }}"
        cluster_media_user: "{{ lookup('env', 'CLUSTER_MEDIA_USER') }}"
        ssh_key: "{{ lookup('env', 'CLUSTER_SSH_KEY') }}"
        ansible_ssh_common_args: '-l {{ cluster_user}} -o ProxyCommand="ssh -i {{ ssh_key }} -W %h:%p -q {{ cluster_user }}@{{ cluster_head_node }}"'
    children:
        cluster:
            hosts:
        gatewayed:
            hosts:
